/*
 * This file is generated by jOOQ.
 */
package com.kanban.jooq;


import com.kanban.jooq.tables.Boards;
import com.kanban.jooq.tables.Columns;
import com.kanban.jooq.tables.Subtasks;
import com.kanban.jooq.tables.Tasks;
import com.kanban.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.boards</code>.
     */
    public final Boards BOARDS = Boards.BOARDS;

    /**
     * The table <code>public.columns</code>.
     */
    public final Columns COLUMNS = Columns.COLUMNS;

    /**
     * The table <code>public.subtasks</code>.
     */
    public final Subtasks SUBTASKS = Subtasks.SUBTASKS;

    /**
     * The table <code>public.tasks</code>.
     */
    public final Tasks TASKS = Tasks.TASKS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Boards.BOARDS,
            Columns.COLUMNS,
            Subtasks.SUBTASKS,
            Tasks.TASKS,
            Users.USERS);
    }
}
