/*
 * This file is generated by jOOQ.
 */
package com.kanban.jooq;


import com.kanban.jooq.tables.Boards;
import com.kanban.jooq.tables.Columns;
import com.kanban.jooq.tables.FlywaySchemaHistory;
import com.kanban.jooq.tables.Subtasks;
import com.kanban.jooq.tables.Tasks;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.boards</code>.
     */
    public static final Boards BOARDS = Boards.BOARDS;

    /**
     * The table <code>public.columns</code>.
     */
    public static final Columns COLUMNS = Columns.COLUMNS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.subtasks</code>.
     */
    public static final Subtasks SUBTASKS = Subtasks.SUBTASKS;

    /**
     * The table <code>public.tasks</code>.
     */
    public static final Tasks TASKS = Tasks.TASKS;
}
