/*
 * This file is generated by jOOQ.
 */
package com.kanban.jooq.tables.records;


import com.kanban.jooq.tables.Tasks;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TasksRecord extends UpdatableRecordImpl<TasksRecord> implements Record6<UUID, String, String, String, UUID, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.tasks.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tasks.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.tasks.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tasks.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tasks.status</code>.
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tasks.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tasks.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tasks.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tasks.column_id</code>.
     */
    public void setColumnId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tasks.column_id</code>.
     */
    public UUID getColumnId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.tasks.position</code>.
     */
    public void setPosition(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tasks.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, String, String, UUID, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, String, String, String, UUID, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Tasks.TASKS.ID;
    }

    @Override
    public Field<String> field2() {
        return Tasks.TASKS.DESCRIPTION;
    }

    @Override
    public Field<String> field3() {
        return Tasks.TASKS.STATUS;
    }

    @Override
    public Field<String> field4() {
        return Tasks.TASKS.TITLE;
    }

    @Override
    public Field<UUID> field5() {
        return Tasks.TASKS.COLUMN_ID;
    }

    @Override
    public Field<Integer> field6() {
        return Tasks.TASKS.POSITION;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public String component3() {
        return getStatus();
    }

    @Override
    public String component4() {
        return getTitle();
    }

    @Override
    public UUID component5() {
        return getColumnId();
    }

    @Override
    public Integer component6() {
        return getPosition();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public String value3() {
        return getStatus();
    }

    @Override
    public String value4() {
        return getTitle();
    }

    @Override
    public UUID value5() {
        return getColumnId();
    }

    @Override
    public Integer value6() {
        return getPosition();
    }

    @Override
    public TasksRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public TasksRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TasksRecord value3(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public TasksRecord value4(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public TasksRecord value5(UUID value) {
        setColumnId(value);
        return this;
    }

    @Override
    public TasksRecord value6(Integer value) {
        setPosition(value);
        return this;
    }

    @Override
    public TasksRecord values(UUID value1, String value2, String value3, String value4, UUID value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TasksRecord
     */
    public TasksRecord() {
        super(Tasks.TASKS);
    }

    /**
     * Create a detached, initialised TasksRecord
     */
    public TasksRecord(UUID id, String description, String status, String title, UUID columnId, Integer position) {
        super(Tasks.TASKS);

        setId(id);
        setDescription(description);
        setStatus(status);
        setTitle(title);
        setColumnId(columnId);
        setPosition(position);
    }
}
